; Map File written automatically by HHPMod Version 3.2.2
; octubre 04, 2015, 03:12 
;
#define Virtual_nodes 122
#define TreeType_notes 120
#define KeyNote_editor 100
#define Options_Actions 211
#define Options_Confirmations 212
#define Options_Chrome 213
#define Options_Tab_icons 214
#define Options_Advanced 215
#define Options_Formats 216
#define Options_Clipboard_capture 217
#define Options_File_types 218
#define Options_File_Options 210
#define File_properties_Information 231
#define File_properties_Settings 232
#define File_properties_File_icons 233
#define File_properties_Security 234
#define KeyNote_File_properties 230
#define Note_properties_Note_settings 251
#define Note_properties_Tree_settings 252
#define Note_properties_Advanced 253
#define About_initial_fonts_and_colors_in_KeyNote 255
#define Note_properties_and_defaults 250
#define Configuration_options 205
#define Options_General_settings 206
#define Options_Rich_Text_editor 207
#define Options_Tree_panel 208
#define Options_KeyNote_Files 209
#define Configuring_KeyNote_Overview 200
#define KeyNote_menus_View 315
#define KeyNote_menus_Edit 310
#define KeyNote_menus_Format 325
#define KeyNote_menus_Insert 320
#define KeyNote_menus_Tree 335
#define KeyNote_menus_Note 330
#define KeyNote_menus_Tools 345
#define KeyNote_menus_Search 340
#define KeyNote_menus_Help 355
#define KeyNote_menus_File 305
#define KeyNote_menus 300
#define Styles 515
#define Sending_KeyNote_files_by_Email 510
#define Hyperlinks 525
#define Integration_with_WordWeb 520
#define Plugins 535
#define Macros 530
#define Word_expansion_glossary 550
#define File_manager 560
#define Clipboard_capture 575
#define Insert_character_dialog_box 570
#define Importing_files_as_notes 585
#define Expression_evaluation 580
#define Exporting_notes_to_disk_files 590
#define Encrypting_KeyNote_files 505
#define Special_Functions 500
#define KeyNote_Is_OpenSource 11
#define Whats_New 12
#define Quick_Start 15
#define Welcome_Keynote 10
#define Acknowledgments 22
#define KeyNote_on_the_web 24
#define Hints_and_tips 25
#define OtherFreewarefrGZ 26
#define Features 20
#define Command_Line_Reference 35
#define Keyboard_Reference 30
#define Known_Problems_and_Bugs 45
#define Information_For_Dart_Notes_Users 40
#define Auxiliary_Files 55
#define License 50
#define Sharing_KeyNote_on_a_multiuser_system 60
